import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    // Navbar & Session
    nav_logo_panel: "Panel",
    nav_test_sound: "Test Sound",
    nav_logout: "Logout",
    nav_loading: "Loading...",
    
    // Home Page
    home_badge: "For Street Food Vendors & Food Trucks",
    home_title_1: "Modernize your food stall with ",
    home_title_2: "Kantina",
    home_subtitle: "Your customers scan a QR code, choose their favorite dishes, and you receive orders and payments instantly on your phone. No lines, no errors, no hassle.",
    home_btn_start: "Get Started",
    home_btn_demo: "View Demo",
    home_feat_qr_title: "Autogenerated QR Code",
    home_feat_qr_desc: "Download and print your unique QR code. Place it on your tables so customers can order without installing any apps.",
    home_feat_live_title: "Real-Time Orders",
    home_feat_live_desc: "Get notified instantly with sounds and flashing titles every time a new order lands in your digital kitchen.",
    home_feat_menu_title: "Manage Your Menu",
    home_feat_menu_desc: "Modify prices, add new items, or instantly toggle availability for dishes that are sold out for the day.",
    home_footer: "© {year} Kantina. Designed to empower local commerce.",
    home_access_vendors: "Vendor Access",

    // Login Page
    login_title: "Sign In",
    login_subtitle: "Vendor Control Panel",
    login_label_email: "Email Address",
    login_label_password: "Password",
    login_btn_submit: "Enter my Kantina",
    login_back: "← Back to Home",
    login_err_fields: "Please fill in all fields.",
    login_err_credential: "Incorrect credentials. Please try again.",
    login_err_connection: "Connection error. Please try again later.",
    
    // Dashboard Stats
    stats_active: "Active Orders",
    stats_earnings: "Today's Earnings",
    stats_completed: "Completed Orders",
    
    // Demo Mode Bar
    demo_mode_notice: "Demo Mode active: Data is saved locally in your browser.",
    demo_mode_btn: "Simulate New Order",
    demo_mode_menu_warning: "Please add some dishes to your menu first.",
    demo_mode_available_warning: "You must have at least one available dish to receive orders.",

    // Dashboard Tabs
    tab_active: "Active Orders",
    tab_history: "History",
    tab_menu: "My Menu",
    tab_qrcode: "QR Code",

    // Kanban Columns
    col_pending: "To Confirm",
    col_preparing: "In Kitchen",
    col_ready: "Ready for Pickup",
    col_pending_empty: "No new orders",
    col_preparing_empty: "Kitchen is clear",
    col_ready_empty: "Nothing ready yet",
    col_empty_footer: "New orders will appear here automatically.",

    // Order Card
    order_id: "Order",
    order_total: "Total Collected",
    order_btn_prepare: "Prepare",
    order_btn_ready: "Ready",
    order_btn_complete: "Complete",
    order_btn_cancel_title: "Cancel Order",
    order_notes_placeholder: "Notes",
    order_time_moment: "Just now",
    order_time_mins: "X min(s) ago",
    order_time_hours: "X hr(s) ago",

    // History Tab
    history_title: "Order History",
    history_subtitle: "List of completed or cancelled orders for the day.",
    history_empty: "No history accumulated today",
    history_empty_desc: "Completed orders will move to this tab.",
    history_th_id: "ID",
    history_th_customer: "Customer",
    history_th_details: "Details",
    history_th_total: "Total",
    history_th_status: "Status",
    history_th_time: "Time",
    history_status_completed: "Completed",
    history_status_cancelled: "Cancelled",

    // Menu Editor
    menu_title: "Menu Editor",
    menu_subtitle: "Add, edit, or disable items in your restaurant catalog.",
    menu_btn_add: "Add Dish",
    menu_btn_close: "Close Form",
    menu_form_new_title: "New Dish",
    menu_form_edit_title: "Edit Dish",
    menu_form_name: "Dish Name",
    menu_form_name_placeholder: "e.g. Pastor Tacos",
    menu_form_price: "Price ($ USD)",
    menu_form_category: "Category",
    menu_form_description: "Short description (optional)",
    menu_form_desc_placeholder: "e.g. With pineapple, onions, cilantro, and double tortilla.",
    menu_form_save: "Save Dish",
    menu_form_cancel: "Cancel",
    menu_form_empty: "Your menu is empty",
    menu_form_empty_desc: "Create dishes above to start receiving orders.",
    menu_confirm_delete: "Are you sure you want to delete this dish from your menu?",
    menu_available: "Available",
    menu_sold_out: "Sold Out",

    // QR Code Page
    qr_title: "Menu QR Code",
    qr_subtitle: "Show or print this QR code so your customers can place orders.",
    qr_frame_title: "KANTINA",
    qr_frame_subtitle: "SCAN & ORDER FROM YOUR PHONE",
    qr_frame_spot: "Table or Spot #1",
    qr_btn_download: "Download PNG",
    qr_btn_share: "Share Link",
    qr_copied_alert: "Menu link copied to clipboard!",
    qr_link_label: "Your Menu Link",
    qr_how_title: "How does it work?",
    qr_how_step_1: "Download and print the QR code on paper or stickers.",
    qr_how_step_2: "Place it visibly on your tables, counter, or food cart.",
    qr_how_step_3: "Your customers scan the code, browse the menu, and order instantly. You will receive notifications here!",

    // Customer Menu Page
    customer_menu_tag: "KANTINA MENU",
    customer_menu_sub: "Order instantly in a couple of clicks",
    customer_menu_todos: "All",
    customer_menu_empty: "Menu currently unavailable",
    customer_menu_empty_desc: "The vendor has not enabled dishes in this section yet.",
    customer_cart_bar: "Review Order",
    customer_cart_title: "My Order",
    customer_cart_qty_price: "X x $Y",
    customer_form_name: "Who is this for? / Table #",
    customer_form_name_placeholder: "e.g. John Doe (Table 4)",
    customer_form_notes: "Special instructions (optional)",
    customer_form_notes_placeholder: "e.g. No onions, extra salsa, napkins...",
    customer_form_payment_method: "Payment method",
    customer_form_payment_val: "Cash on delivery",
    customer_form_btn_confirm: "Confirm Order 🍽️",
    customer_subtotal: "Subtotal",
    customer_total: "Total",
    customer_err_name: "Please enter your name or table number.",
    customer_err_create: "There was a problem creating your order: {error}",
    customer_err_connection: "Connection error. Please try again.",

    // Order Status Page
    status_header_label: "Order Tracking",
    status_not_found_title: "Order not found",
    status_not_found_desc: "We couldn't locate the specified order. Please check the link or contact the vendor.",
    status_not_found_btn: "Go to Home",
    status_stage_cancelled: "Order Cancelled",
    status_stage_cancelled_desc: "We are sorry, your order has been cancelled by the kitchen. Please check at the counter.",
    status_stage_delivered: "Order Delivered!",
    status_stage_delivered_desc: "Thank you for your purchase! We hope you enjoy your food. Bon appétit!",
    status_step_received: "Received",
    status_step_received_desc: "Sent to the kitchen, waiting for confirmation.",
    status_step_cooking: "Cooking",
    status_step_cooking_desc: "Your order is being prepared right now!",
    status_step_ready: "Ready",
    status_step_ready_desc: "Delicious! Pass by to pick up your order.",
    status_details_title: "Order details",
    status_footer_notice: "📍 Please do not close this tab. It will update automatically when your food is ready.",
    status_back_menu: "← Back to Menu",
    status_back_dashboard: "Go to Vendor Dashboard →"
  },
  es: {
    // Navbar & Session
    nav_logo_panel: "Panel",
    nav_test_sound: "Probar Sonido",
    nav_logout: "Cerrar Sesión",
    nav_loading: "Cargando...",

    // Home Page
    home_badge: "Para Vendedores Ambulantes y Comida Callejera",
    home_title_1: "Moderniza tu puesto de comida con ",
    home_title_2: "Kantina",
    home_subtitle: "Tus clientes escanean un código QR, eligen sus platillos favoritos y tú recibes los pedidos y pagos al instante en tu celular. Sin filas, sin errores, sin complicaciones.",
    home_btn_start: "Comenzar Ahora",
    home_btn_demo: "Ver Demostración",
    home_feat_qr_title: "Código QR Autogenerado",
    home_feat_qr_desc: "Descarga e imprime tu código QR único. Colócalo en tus mesas para que tus comensales ordenen sin necesidad de instalar apps.",
    home_feat_live_title: "Pedidos en Tiempo Real",
    home_feat_live_desc: "Entérate al instante mediante notificaciones y sonidos cada vez que entra un nuevo pedido a tu cocina digital.",
    home_feat_menu_title: "Administra tu Menú",
    home_feat_menu_desc: "Modifica precios, agrega nuevos platillos o desactiva de forma inmediata las opciones que se hayan agotado en el día.",
    home_footer: "© {year} Kantina. Diseñado para empoderar el comercio local.",
    home_access_vendors: "Acceso Vendedores",

    // Login Page
    login_title: "Iniciar Sesión",
    login_subtitle: "Panel de Control de Vendedores",
    login_label_email: "Correo Electrónico",
    login_label_password: "Contraseña",
    login_btn_submit: "Ingresar a mi Kantina",
    login_back: "← Volver al Inicio",
    login_err_fields: "Por favor llena todos los campos.",
    login_err_credential: "Credenciales incorrectas. Intenta de nuevo.",
    login_err_connection: "Error de conexión. Intenta más tarde.",

    // Dashboard Stats
    stats_active: "Pedidos en Curso",
    stats_earnings: "Ventas del Día",
    stats_completed: "Pedidos Completados",

    // Demo Mode Bar
    demo_mode_notice: "Modo Demostración activo: Los datos se guardan de forma local en tu navegador.",
    demo_mode_btn: "Simular Pedido Entrante",
    demo_mode_menu_warning: "Primero agrega algunos platillos a tu menú.",
    demo_mode_available_warning: "Debes tener al menos un platillo disponible para recibir un pedido.",

    // Dashboard Tabs
    tab_active: "Pedidos Activos",
    tab_history: "Historial",
    tab_menu: "Mi Menú",
    tab_qrcode: "Código QR",

    // Kanban Columns
    col_pending: "Por Confirmar",
    col_preparing: "En Cocina",
    col_ready: "Listo para Entrega",
    col_pending_empty: "Sin pedidos nuevos",
    col_preparing_empty: "Cocina despejada",
    col_ready_empty: "Nada listo para recoger",
    col_empty_footer: "Los nuevos pedidos aparecerán aquí automáticamente.",

    // Order Card
    order_id: "Orden",
    order_total: "Total Cobrado",
    order_btn_prepare: "Preparar",
    order_btn_ready: "Listo",
    order_btn_complete: "Completar",
    order_btn_cancel_title: "Cancelar Pedido",
    order_notes_placeholder: "Notas",
    order_time_moment: "Hace un momento",
    order_time_mins: "Hace X min(s)",
    order_time_hours: "Hace X hr(s)",

    // History Tab
    history_title: "Historial de Pedidos",
    history_subtitle: "Listado de pedidos completados o cancelados del día.",
    history_empty: "Sin historial acumulado hoy",
    history_empty_desc: "Los pedidos completados se trasladarán a esta pestaña.",
    history_th_id: "ID",
    history_th_customer: "Cliente",
    history_th_details: "Detalle",
    history_th_total: "Total",
    history_th_status: "Estado",
    history_th_time: "Hora",
    history_status_completed: "Completado",
    history_status_cancelled: "Cancelado",

    // Menu Editor
    menu_title: "Editor del Menú",
    menu_subtitle: "Agrega, edita o deshabilita los platillos de tu carta.",
    menu_btn_add: "Agregar Platillo",
    menu_btn_close: "Cerrar Formulario",
    menu_form_new_title: "Nuevo Platillo",
    menu_form_edit_title: "Editar Platillo",
    menu_form_name: "Nombre del Platillo",
    menu_form_name_placeholder: "Ej. Tacos al Pastor",
    menu_form_price: "Precio ($ MXN)",
    menu_form_category: "Categoría",
    menu_form_description: "Descripción corta (opcional)",
    menu_form_desc_placeholder: "Ej. Con piña, cilantro, cebolla y copia de tortilla.",
    menu_form_save: "Guardar Platillo",
    menu_form_cancel: "Cancelar",
    menu_form_empty: "Tu menú está vacío",
    menu_form_empty_desc: "Crea platillos arriba para empezar a recibir pedidos.",
    menu_confirm_delete: "¿Seguro que deseas eliminar este platillo de tu menú?",
    menu_available: "Disponible",
    menu_sold_out: "Agotado",

    // QR Code Page
    qr_title: "Código QR del Menú",
    qr_subtitle: "Muestra o imprime este código QR para que tus clientes hagan pedidos.",
    qr_frame_title: "KANTINA",
    qr_frame_subtitle: "ESCANEA Y PIDE DESDE TU MÓVIL",
    qr_frame_spot: "Mesa o Puesto #1",
    qr_btn_download: "Descargar PNG",
    qr_btn_share: "Compartir Link",
    qr_copied_alert: "¡Enlace de menú copiado al portapapeles!",
    qr_link_label: "Enlace de tu menú",
    qr_how_title: "¿Cómo funciona?",
    qr_how_step_1: "Descarga e imprime el código QR en papel o calcomanías.",
    qr_how_step_2: "Colócalo visible en tus mesas, barra o en tu puesto de comida.",
    qr_how_step_3: "Tus clientes escanean el código con su celular, ven el menú y ordenan al instante. ¡Recibirás las notificaciones aquí!",

    // Customer Menu Page
    customer_menu_tag: "KANTINA MENU",
    customer_menu_sub: "Pide al instante en un par de clics",
    customer_menu_todos: "Todos",
    customer_menu_empty: "Menú no disponible por el momento",
    customer_menu_empty_desc: "El vendedor no ha habilitado platillos en esta sección.",
    customer_cart_bar: "Ver Pedido",
    customer_cart_title: "Mi Orden",
    customer_cart_qty_price: "X x $Y",
    customer_form_name: "¿A nombre de quién? / Mesa",
    customer_form_name_placeholder: "Ej. Juan Pérez (Mesa 4)",
    customer_form_notes: "Instrucciones especiales (opcional)",
    customer_form_notes_placeholder: "Ej. Sin cebolla, salsa extra, servilletas...",
    customer_form_payment_method: "Método de pago",
    customer_form_payment_val: "Efectivo al Recibir",
    customer_form_btn_confirm: "Confirmar Pedido 🍽️",
    customer_subtotal: "Subtotal",
    customer_total: "Total",
    customer_err_name: "Por favor ingresa tu nombre o número de mesa.",
    customer_err_create: "Hubo un problema al crear tu pedido: {error}",
    customer_err_connection: "Error de conexión. Intenta de nuevo.",

    // Order Status Page
    status_header_label: "Seguimiento de Pedido",
    status_not_found_title: "Pedido no encontrado",
    status_not_found_desc: "No pudimos localizar la orden especificada. Por favor verifica el enlace o contacta al vendedor.",
    status_not_found_btn: "Ir al Inicio",
    status_stage_cancelled: "Pedido Cancelado",
    status_stage_cancelled_desc: "Lo sentimos, tu pedido ha sido cancelado por el puesto. Por favor acércate al mostrador para más información.",
    status_stage_delivered: "¡Pedido Entregado!",
    status_stage_delivered_desc: "¡Muchas gracias por tu compra! Esperamos que disfrutes tu comida. ¡Buen provecho!",
    status_step_received: "Recibido",
    status_step_received_desc: "Enviado a la cocina, en espera de confirmación.",
    status_step_cooking: "Cocinando",
    status_step_cooking_desc: "¡Tu pedido se está preparando en este momento!",
    status_step_ready: "Listo",
    status_step_ready_desc: "¡Buenísimo! Pasa a recoger tu pedido.",
    status_details_title: "Detalle de tu orden",
    status_footer_notice: "📍 Por favor, no cierres esta pestaña. Se actualizará sola cuando tu comida esté lista.",
    status_back_menu: "← Volver al Menú",
    status_back_dashboard: "Ir al Dashboard de Vendedor →"
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('kantina_language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('kantina_language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => (prev === 'en' ? 'es' : 'en'));
  };

  /**
   * Translates a translation key with parameter formatting.
   * @param {string} key
   * @param {object} params Replace values inside key dynamically.
   * @returns {string} Translated string.
   */
  const t = (key, params = {}) => {
    const dict = translations[language] || translations['en'];
    let text = dict[key] || translations['en'][key] || key;

    // Handle string replacements, e.g. "© {year}" -> "© 2026"
    Object.keys(params).forEach(paramKey => {
      text = text.replace(`{${paramKey}}`, params[paramKey]);
    });

    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
